### ISSUE TITLE
Issue with Kaya-cli and ../data

### ISSUE THREAD

**Issue by csajedi** [Zilliqa/kaya#84]
I've been having several problems with Kaya on windows so now I'm using NVM and virtualbox in an attempt to bypass the issues. However, it seems that npm install -g kaya-cli will result in some problems regarding permissions in its relative path. Full output of my error:

> ~ kaya-cli -f         
ZILLIQA KAYA RPC SERVER (ver: 0.2.9)
Server listening on 127.0.0.1:4200
Running from remote interpreter
https://scilla-runner.zilliqa.com/contract/call
================================================================================
fs.js:114
    throw err;
    ^

> Error: EACCES: permission denied, mkdir '../data/'
    at Object.mkdirSync (fs.js:757:3)
    at Object.prepareDirectories (/home/cameron/.nvm/versions/node/v10.16.0/lib/node_modules/kaya-cli/src/utilities.js:177:10)
    at Object.<anonymous> (/home/cameron/.nvm/versions/node/v10.16.0/lib/node_modules/kaya-cli/src/app.js:89:7)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (/home/cameron/.nvm/versions/node/v10.16.0/lib/node_modules/kaya-cli/src/server.js:38:13)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:829:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)

There is an open issue that may fix this by removing relative paths: https://github.com/Zilliqa/kaya/issues/78 , but it may have gone stale. If we were to move to a database, what would it be? a sqlite DB stored in $HOME/.kaya ? If I have time in a couple weeks I may attempt a fix and submit pull request.

**Comment by edisonljh** [comment]
I plan to refactor it in Q3 to include a few features, including storing the state files in a database like leveldb.

Apologies but I haven't got time to work on it soon. But if you could make a PR, that will be good. A few users have complained about the `kaya-cli` and relative filepath issue.
