### ISSUE TITLE
npm install error in scrypt

### ISSUE THREAD

**Issue by vkomenda** [Zilliqa/kaya#89]
Do you know how to fix C compilation errors during the `npm i -g kaya-cli` step?

```
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:37:36: error: no matching function for call to ‘v8::Value::IntegerValue()’
   37 |       maxmem(info[2]->IntegerValue()),
      |                                    ^
In file included from ../src/node-boilerplate/scrypt_params_async.cc:4:
../src/node-boilerplate/inc/scrypt_params_async.h:38:39: error: no matching function for call to ‘v8::Value::IntegerValue()’
   38 |       osfreemem(info[3]->IntegerValue())
      | 
```

The `npm` error message is as follows:
```
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/vk/.npm-global/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:196:23)
gyp ERR! stack     at ChildProcess.emit (events.js:209:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.2.0-2-amd64
gyp ERR! command "/home/vk/.npm-global/lib/node_modules/node/bin/node" "/home/vk/.npm-global/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/vk/.npm-global/lib/node_modules/kaya-cli/node_modules/scrypt
gyp ERR! node -v v12.9.1
gyp ERR! node-gyp -v v5.0.3
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/vk/.npm/_logs/2019-09-07T13_28_09_557Z-debug.log
```

I thought that might be related to #74 but setting the suggested solution involving `python` variable in `~/.npmrc` doesn't change anything.

**Comment by SvenMeyer** [comment]
I had the same problem with node v12.13.1 , switching to node v10.17.0 worked.
